### ISSUE TITLE
Tauri v2-beta permission errors

### ISSUE THREAD

**Issue by liyasthomas** [FabianLars/tauri-plugin-oauth#13]
Tauri v2.0.0-beta gives the following permission error.

<img width="882" alt="Screenshot 2024-03-21 at 8 25 53 PM" src="https://github.com/FabianLars/tauri-plugin-oauth/assets/10395817/fbed5f21-02fc-4597-85a3-7926451bb5fd">

**Comment by FabianLars** [comment]
there should be a capability file in src-tauri/capabilities with a bunch of `permissions`, just add "oauth:allow-start" to that array.
