### ISSUE TITLE
I gues

### ISSUE THREAD

**Issue by rtiagom** [FabianLars/tauri-plugin-oauth#14]
More of a question than an issue..

I was trying the plugin with Apple Sign-in and it requires the redirect_uri to be a domain not a localhost or an IP address. Just want to confirm I'm not misunderstanding and basically the plugin will not work in this case right? Any other alternatives apart from using Swift or something like [objc2-authentication-services](https://github.com/madsmtm/objc2/tree/master/framework-crates/objc2-authentication-services) ?

**Comment by FabianLars** [comment]
Correct, this plugin serves solely the oppsite use-case. It was created for oauth implementations that require, or work better, with localhost redirect_uris (initially this was about deep links vs localhost, not a https requirement, but it still applies).

I don't know much about apple's requirements but if don't need cross-platform support than what you linked is probably best, though a swift solution via swift-rs would probably also work if it can link against that framework.
If you need cross platform support then you probably won't get around a small website i guess.
